sabang/blueprints/admin/views.py
from flask import (
    Blueprint,
    render_template,
    flash,
    request,
    redirect,
    url_for)

from flask_login import (
    login_required,
    current_user)

from sabang.database.employee_models import Employee
from .forms import UpdateForm

# var = Blueprint('name_of_bp')
admin = Blueprint('admin', __name__, template_folder='templates')

@admin.route('/dashboard')
@login_required
def dashboard():
    return render_template('admin/dashboard.html')

@admin.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    # Will automatically populare form with user properties
    form = UpdateForm(obj=current_user)
    # Populate form with existing user data
    # form.first_name.data = current_user.first_name

    if form.validate_on_submit():
        print 'FORM UPDATING'
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')
        current_user.first_name = request.form.get('first_name')
        current_user.last_name = request.form.get('last_name')

        if new_password:
            current_user.password = Employee.encrypt_password(new_password)
        
        current_user.save()
        flash('Your details are updated!', 'success')
        return redirect(url_for('admin.dashboard'))
    if form.errors:
        flash(form.errors, 'danger')
    return render_template('admin/profile.html', form=form)

  

sabang/blueprints/apartments/views.py
from flask import (
    Blueprint,
    render_template,
    flash,
    request,
    redirect,
    url_for,
    jsonify)

from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

from sabang.database.apartment_models import Apartment
from sabang.utils.room_helpers import parse_room_data, selected_room_data

apartments = Blueprint('apartments', __name__, template_folder='templates')

@apartments.route('/', methods=['GET', 'POST'])
@login_required
def apartments_index():
    apt_list = Apartment.query.all()
    data = parse_room_data(apt_list)
    return render_template('apartments/index.html', apartment_list=data)

@apartments.route('/apartment_detail/<int:id>', methods=['GET', 'POST'])
@login_required
def apartments_detail(id):
    apt = Apartment.query.get(id)
    apt_data = selected_room_data(apt)
    print 'CHECK THE IMG URL!!!'
    print apt_data
    return render_template('apartments/apt_detail.html', apartment=apt_data)

sabang/blueprints/rooms/views.py
from flask import (
    Blueprint,
    render_template)

from flask_login import login_required

from sabang.database.room_models import Room
from sabang.utils.room_helpers import parse_room_data, selected_room_data

rooms = Blueprint('rooms', __name__, template_folder='templates')

@rooms.route('/', methods=['GET', 'POST'])
@login_required
def rooms_index():
    room_list = Room.query.all()
    data = parse_room_data(room_list)
    return render_template('rooms/index.html', room_list=data)


@rooms.route('/room_detail/<int:id>', methods=['GET', 'POST'])
@login_required
def room_detail(id):
    room = Room.query.get(id)
    room_data = selected_room_data(room)
    print "ROOOOMZZZZ"
    print room_data
    return render_template('rooms/room_detail.html', room=room_data)

sabang/blueprints/website/views.py
from flask import (
    Blueprint,
    render_template,
    flash,
    redirect,
    request,
    url_for
)

from sabang.database.room_models import Room
from sabang.database.apartment_models import Apartment
from sabang.blueprints.website.forms import ContactForm
from sabang.blueprints.website.utils import parse_room_data

website = Blueprint('website', __name__, template_folder='templates')


@website.route('/', methods=['GET'])
def index():
    return render_template('website/index.html')

@website.route('/about_us', methods=['GET'])
def about_us():
    return render_template('website/about_us.html')

@website.route('/rooms', methods=['GET'])
def rooms():
    room_data = parse_room_data(Room.query.all())
    return render_template('website/rooms.html', rooms=room_data)

@website.route('/restaurant', methods=['GET'])
def restaurant():
    return render_template('website/restaurant.html')

@website.route('/apartments', methods=['GET'])
def apartments():
    aparmtent_data = parse_room_data(Apartment.query.all())
    print(aparmtent_data)
    return render_template('website/apartments.html', apartments=aparmtent_data)

@website.route('/diving', methods=['GET'])
def diving():
    return render_template('website/diving.html')

@website.route('/packages', methods=['GET'])
def packages():
    return render_template('website/packages.html')

@website.route('/contact', methods=['GET', 'POST'])
def contact_us():
    form = ContactForm()

    # Differentiaes GET/POST requests
    # validate_on_submit() is from WTForms
    # If form is submit, and no errors then everything below is executed
    # This is a "POST"
    if form.validate_on_submit():
        from sabang.blueprints.website.tasks import send_contact_form

        # .delay tells Celery we want task to run in background
        send_contact_form.delay(
            request.form.get('email'),
            request.form.get('message'))
        
        # Allows us to display Flask Flash message
        # Message is seen after being redirected
        # Send 'success' to style with Bootstrap
        flash("Thanks for the message, we will get back to you shortly!", 'success')
        # Redirect back to contact page - This will allow for form to be cleared
        return redirect(url_for('website.contact_us'))
    # GET requests
    # We send the form arguement to the jinja2 template
    return render_template('website/contact_us.html', form=form)

sabang/templates/layouts/admin_base.html
{% import 'macros/flash.html' as flash with context %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Sabang Inn - Admin</title>
    <script src="{{ url_for('static', filename='scripts/vendor/jquery-3.2.1.min.js') }}"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <link href="{{ url_for('static', filename='styles/main.css') }}" rel="stylesheet">
    <style>
        body {
            background-color: #f2f2f2;
        }
        body .container {
            padding: 60px 15px;
        }

        table {
            margin-top: 25px;   
        }
    </style>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{ url_for('auth.login') }}">SABANG INN</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('admin.dashboard') }}">Dashboard <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('rooms.rooms_index') }}">Rooms</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('apartments.apartments_index') }}">Apartments</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('admin.profile') }}">Profile</a>
              </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {{ flash.render() }}
        {% block content %} {% endblock %}
    </div>
    <script src="{{ url_for('static', filename='scripts/helpers.js') }}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        

    </script>
</body>

</html>

sabang/templates/layouts/web_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sabang Inn</title>
  <link href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='styles/vendor/lightbox.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='styles/vendor/font-awesome.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='styles/main-style.css') }}" rel="stylesheet" />
  <link href="{{ url_for('static', filename='styles/home-style.css') }}" rel="stylesheet" />
  <link href="{{ url_for('static', filename='styles/apartment-style.css') }}" rel="stylesheet" />
  <link href="{{ url_for('static', filename='styles/room-style.css') }}" rel="stylesheet" />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <img src="{{ url_for('static', filename='images/logo.png') }}" /> Sabang Inn
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('website.index') }}">HOME</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ABOUT <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('website.about_us') }}">About Sabang Inn</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ACCOMODATIONS <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('website.rooms') }}">Rooms</a></li>
                        <li><a href="{{ url_for('website.apartments') }}">Apartments</a></li>
                    </ul>
                </li>
                <li><a href="{{ url_for('website.diving') }}">DIVING</a></li>
                <li><a href="{{ url_for('website.restaurant') }}">RESTAURANT</a></li>
                <li><a href="{{ url_for('website.packages') }}">PACKAGES</a></li>
                <li><a href="{{ url_for('website.contact_us') }}">CONTACT US</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
  {% block content %} 
  
  {% endblock %}
</div>
  <section class="container-fluid footerSection"> 
            <div class="container-fluid footer">
                <div class="row footer-top text-center">
                    <p class="footerLinks" style="margin: 15px 0 7px;">
                        <a href="#" style="color:#92C4E2">Home</a> ·
                        <a href="#" style="color:#92C4E2">Directions</a> ·
                        <a href="#" style="color:#92C4E2">Diving</a> ·
                        <a href="#" style="color:#92C4E2">Terms & Conditions</a>
                    </p>
                </div>
                <div class="row footer-main">
                    <div class="col-lg-12 footerCenter" style="text-align:center;">
                        <div class="col-lg-4" style="padding-top: 15px">
                            <img src="{{ url_for('static', filename='images/logo.png') }}" class="animated bounce" style="height:60px; margin-bottom:5px;" />
                            <p class="footerCompanyName" style="color:#292C2F">Sabang Inn &copy; 2018</p>
                        </div>
                        <div class="col-lg-4">
                            <div class="row">
                                <div class="col-lg-2" style="margin-top:10px;"><i class="fa fa-map-marker socialIcons"></i></div>
                                <div class="col-lg-8">
                                    <p>Sabang Beach, Puerto Galera</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-2"><i class="fa fa-phone socialIcons" style="margin-bottom:10px"></i></div>
                                <div class="col-lg-8">
                                    <p>+63 917 572 6123</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-2"><i class="fa fa-envelope socialIcons"></i></div>
                                <div class="col-lg-8">
                                    <p><a href="mailto:info@sabanginn.com" style="color:#92C4E2">info@sabanginn.com</a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="row" style="margin-top:-5px;">
                                <div class="col-lg-12">
                                    <p style="text-align:center">Follow Us</p>
                                    <a href="https://www.facebook.com/sabanginn.diverdream"><i class="fa fa-facebook socialIcons"></i></a>
                                </div>
                                <div class="col-lg-12" style="margin-top:15px; text-align:center;">
                                    <div class="col-lg-12">
                                        <p>Designed By: <a style="color:#92C4E2">Code Sage Solutions</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <script src="{{ url_for('static', filename='scripts/vendor/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/lightbox.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/helpers.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/navbar.js') }}"></script>
  <script src="{{ url_for('static', filename='scripts/vendor/wow.min.js') }}"></script>
    <script>
        $('.flip').mouseover(function () {
            $(this).find('.card').addClass('flipped').mouseleave(function () {
                $(this).removeClass('flipped');
            });
            return false;
        });
    </script>
</body>
</html>